apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "raleur-frontend.fullname" . }}
data:
  natsurl: {{ .Values.configMap.natsURL }}
  natsport: {{ .Values.configMap.natsPort }}
  natspost: {{ .Values.configMap.natsPost }}
  natsget: {{ .Values.configMap.natsGet }}